# Generated by Django 2.0 on 2017-12-30 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('locname', models.TextField()),
                ('title', models.TextField()),
                ('_catlist', models.TextField(db_column='binary catlist')),
                ('desc', models.TextField()),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
                ('timetoann', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='_map_instance',
        ),
        migrations.AddField(
            model_name='event',
            name='mapid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmap.Map'),
        ),
    ]
