# Generated by Django 2.0 on 2017-12-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmap', '0002_auto_20171230_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
    ]
