# Generated by Django 2.0 on 2017-12-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmap', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mapid',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
