# Generated by Django 2.0 on 2018-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmap', '0013_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='timetoann',
            field=models.DateTimeField(),
        ),
    ]
